
# Stage 1 Build the React App
FROM node:18.13.0-alpine3.17 as build
WORKDIR /app
COPY . /app/
RUN npm i
RUN npm run build

# CMD ["npm","run","start"]

# Stage 2 Copy the react app to NGINX

FROM nginx:1.23.3-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]

